services:
  - type: web
    name: thecareman28543
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app/dashboard.py --server.address 0.0.0.0 --server.port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
